### ISSUE TITLE
Issues in  running test case in container application deployed on edge-node

### ISSUE THREAD

**Issue by ashishsaxenahsc** [open-ness/edgenode#10]
![Setup](https://user-images.githubusercontent.com/43564844/73834650-15d3fb00-4832-11ea-9c9f-f41432777242.png)
Hi Openness Team,

We have been following the getting started and applications onboarding documentation for deploying Openness and trying to run our test application on Edge Node.

We want to run end-to-end bump in the wire scenario on the setup. 

Attached  is our test setup:
 

We are using On-Premise  mode for deploying the Controller and  Edgenode. 

Test Application is deployed as a container on the Edge Node. All the m/c have ip address in the same subnet. We have created traffic rule to accept the packets with destination ip address 50.50.50.50 . We are pinging the same ip address  from the upstream m/c, and after applying the traffic rule on the test application container ,the icmp request packets are received inside the Container app .

Now , we want the packets to reach the downstream machine. Earlier , on  Openness version 19.09  , we were able to achieve this by adding appropriate route on the container app , but after upgrading to the latest version 19.12 , we are not able to receive the packets at the downstream m/c .
From the nes_client cli , it is observed that the count for received and send packets has been increasing at the KNI interface which means container is sending out the packets  , but the packets are not reaching the downstream interface.
Below are the cli stats:
# show all
ID:          Name:                  Received:                       Sent:           Dropped(TX full):                Dropped(HW):                IP Fragmented(Forwarded):
0  0000:60:00.0                         38258 pkts                  30587 pkts                      0 pkts                      0 pkts                      0 pkts
     (ac:1f:6b:6b:49:84)              10378488 bytes               9747584 bytes                     0 bytes
1  0000:60:00.1                           624 pkts                  31597 pkts                      0 pkts                      0 pkts                      0 pkts
     (ac:1f:6b:6b:49:85)                 47042 bytes               9845566 bytes                     0 bytes
2           KNI                             2 pkts                      0 pkts                      0 pkts                      0 pkts                      0 pkts
     (26:f6:c3:98:bb:5e)                   148 bytes                     0 bytes                     0 bytes
3           KNI                          2857 pkts                      0 pkts                      0 pkts                      0 pkts                      0 pkts
      (not registered)                  476358 bytes                     0 bytes                     0 bytes
4           KNI                          2687 pkts                      0 pkts                      0 pkts                      0 pkts                      0 pkts
      (not registered)                  449010 bytes                     0 bytes                     0 bytes
5           KNI                          2497 pkts                      0 pkts                      0 pkts                      0 pkts                      0 pkts
      (not registered)                  415830 bytes                     0 bytes                     0 bytes
6           KNI                          2074 pkts                      0 pkts                      0 pkts                      0 pkts                      0 pkts
      (not registered)                  344188 bytes                     0 bytes                     0 bytes
7           KNI                          6801 pkts                   6817 pkts                      0 pkts                      0 pkts                      0 pkts
     (ce:8d:eb:0c:fb:18)                668994 bytes                668066 bytes                     0 bytes

Can you please help us in resolving the issue to run our test scenario.

Thanks and Regards,
Ashish

**Comment by anurag-ness** [comment]
Hey Ashish, did you manage to solve your issue? Is there a routing issue either on the edge app or on destination/intermediate gateway side. 

Probably your ingress ports is 0000:60:00.0 - because it recd 38258 pkts 
And your egress port is 0000:60:00.1 because you only got 624 pkts back from network 

If you expect all ingress to egress then the RX/TX on the two should complement. I see the Tx on egress port seems to be sending significant no. of packets but very less RX. So first point to check is that Tx packets are recd at destination but dropped as there is no way of routing them back. 

tcpdump and routing table at destination (or intermediate gateway should give you pointers).

**Comment by ashishsaxenahsc** [comment]
Hi Anurag,
Thanks for the reply.

The problem is resolved now and we are able to see the ping packets at the destination m/c.

Thanks and Regards,
Ashish

**Comment by anurag-ness** [comment]
Thanks Ashish, that is wonderful. It would be great for the forum users if you added a few lines on how did you resolve your issue, was it down to routing, ARP, or firewall etc (each a likely reason).

**Comment by ashishsaxenahsc** [comment]
Hi Anurag,
We upgraded to the latest Openness release "openness-19.12.01_2" and deployed the edge-node in On-Premise IAC mode.
Then , we deploy the test container and apply the traffic rule for allow the destination ip address 50.50.50.50. The route for the dest ip address is added inside the container to send the packets to the KNI interface. After that , the arp is resolved for the destination ip address 50.50.50.50 at the upstream m/c .And after that , when 50.50.50.50 is ping from the upstream m/c , the icmp requst packets are received at the downstream m/c.
