### ISSUE TITLE
Issue in assigning ip address to container app KNI interface through DHCP 

### ISSUE THREAD

**Issue by ashishsaxenahsc** [open-ness/edgenode#11]
Hi Openness Team,

We have deployed edgenode in On-Premise IAC mode our our test setup. We have followed the on-premises-applications-onboarding guide link 
https://github.com/open-ness/specs/blob/master/doc/applications-onboard/on-premises-applications-onboarding.md 
to deploy container app on the edge-node m/c .

Following is our test setup :
![Setup](https://user-images.githubusercontent.com/43564844/75511309-db661400-5a13-11ea-8077-73ae7fb0af07.png)

 

We are following the following steps mentioned in the link  to assgn ip address to the KNI interaface:

docker exec -it <app_docker_id> /bin/bash
ip link set dev vEth2 arp off
ip a a 192.168.10.25/24 dev vEth2
ip link set dev vEth2 up
wget 192.168.10.100 -Y off

Now , I want to assign this ip address dynamically through DHCP . For this, we have configured DHCP server on the downstream machine connected to downstream machine and trying to assign ip address on vEth1 through dhclient.

But vEth1 is not getting any ip address.

Can you please let us know why this is happening and how can we achieve our objective of assigning ip-address dynamically inside container app without running the manual steps mentioned above inside the app container ( ip link set dev vEth2 arp off and wget 192.168.10.100 -Y off commands ) .

Thanks and Regards,
Ashish Saxena

**Comment by anurag-ness** [comment]
Hi Ashish, does the previous ip addr (static one) work ?

**Comment by ashishsaxenahsc** [comment]
Hi Anurag,

Yes , it was working when we were assigning static ip of same subnet on the container App vEth interface.

Now we want to do it with dynamic ip address and without running “wget 192.168.10.100 -Y off “ command in container.

Thanks and Regards,
Ashish

**Comment by amr-mokhtar** [comment]
Hi @ashishsaxenahsc,
The short answer is that **it is not possible to use DHCP with KNI interfaces**.

As a side note, NTS is making decisions on per packet basis and the traffic must be IPv4. Packets will be dropped if neither the source or destination IP are unassigned, this is also true for non Layer 4 packets like ARP.
