### ISSUE TITLE
How to expose App port

### ISSUE THREAD

**Issue by srodriguezOPT** [open-ness/edgenode#12]
Hi OpenNESS team,

I've deployed the controller&node on-premise option and I've instantiated a simply nginx container on the edge node.

App is up and running but 80 port is not exposed even when i made a policy allowing 80 port and 
the port is included in the application configuration:

![imagen](https://user-images.githubusercontent.com/15909508/76064828-bbda6880-5f8a-11ea-8b32-0227bee06f29.png)

![imagen](https://user-images.githubusercontent.com/15909508/76064912-dd3b5480-5f8a-11ea-8d88-db44841280c5.png)

How can I expose this port? I'm looking for something like:

![imagen](https://user-images.githubusercontent.com/15909508/76065326-b7fb1600-5f8b-11ea-89a0-f0852556a690.png)

Thank you

**Comment by amr-mokhtar** [comment]
Hi @srodriguezOPT, This feature is a work-in-progress, but there is a work around t expose the port(s) manually through the docker APIs (didn't try it myself!)

1. Docker container rm $NAME
2. Docker container create – expose $PORT /var/lib/appliance/applications/$NAME
3. Docker container start $NAME

**Comment by amr-mokhtar** [comment]
Hi @srodriguezOPT, from 20.03 release, [port-forwarding](https://github.com/open-ness/specs/blob/master/doc/enhanced-platform-awareness/openness-port-forward.md) feature has became available. Can you try that and let us know if it meet your expectations?

**Comment by srodriguezOPT** [comment]
Hi @amr-mokhtar , thx for the information.

I've just tried 20.03 and now the port-forwarding is working but I can't still maping these exposed ports with the node (host) ports (e.g to access NetApp from outside)

![imagen](https://user-images.githubusercontent.com/15909508/78695139-fb83cf80-78fd-11ea-8a9b-30def3e77148.png)

**Comment by amr-mokhtar** [comment]
Looks like the port mapping is fine. Did you try to add firewall rules for port :8080?

**Comment by srodriguezOPT** [comment]
I think that is not a firewall thing. 

The actual code allows you to expose the ports (80, 8080,...) but does not allow you to publish them with same/different host ports. E.g. you can expose the 80 ports from 2 different containers (applications) and, to avoid the "port in use" error because you need to access those containers from outside, you need to use one of them like 8081 and the other like 8082. Of course you can use the docker_container_ip:exposed_port inside the host, but I need to use the host_ip:published_port to access them from outside.

This option is missing and you need to do it manually as a work around, but the app/platform user does not necessarily has access to the nodes hosts. At the end, I'm talking about to have the same functionality like docker has: "docker run -p HOST_PORT:CONTAINER_PORT" that publish the exposed container port mapping it with the host_port

**Comment by konradja** [comment]
Hi @srodriguezOPT. Indeed it does seem you're correct, we are exposing the port but not publishing it to the host. The workaround, as you said, would be to delete the container on the host and then re-create it with the -p option. We will fix this in the next release, by mapping the container ports (as configured on the UI) to the same ports on the host. To avoid conflicts and keep things simple, every container will have to have a distinct port configured.
