### ISSUE TITLE
Edge Node does not survive a reboot

### ISSUE THREAD

**Issue by higginse-id** [open-ness/edgenode#15]
I have deployed 20.03 on_premise  (onprem_dataplane: "ovncni")

 docker/openness services do not appear appear to be start when an edge node reboots. I don't seem to be able to find any guidelines on the procedure for restarting services.

(Edge node still appears in controller UI, but just returns a 500 error on any attempt to edit)

Currently my only workaround is a full re-deployment via deploy_onprem.sh which isn't practical, particularly when using several edge nodes.

**Comment by amr-mokhtar** [comment]
Hi @higginse-id, state restore after reboot is not supported by OpenNESS on-premises. Regarding the docker service - this is odd. docker service should be enabled by default and automatically restarted after reboot.
Do you see this consistently happening with all nodes? How was docker installed?

**Comment by higginse-id** [comment]
Hi Amr.
  Thanks for the response.

>state restore after reboot is not supported by OpenNESS on-premises
Does this mean that a re-deployment (and subsequent reconfiguration) of controller and all edge nodes is required if any edge node needs to be rebooted?

Is it possible to (re)deploy edge nodes individually?

>Do you see this consistently happening with all nodes? How was docker installed?
The behaviour is repeatable - I didn't install docker, it was installed automatically as part of the deployment.
( I've also seen it before on previous openness releases)

For reference my complete set of customisations to the cloned experience kit (for ne deployment )  is as follows:

As per the documentation I have changed to ovncni in group_vars/all.yml
group_vars/all.yml

onprem_dataplane: "ovncni"

inventory.ini
[all]
on-ctl ansible_ssh_user=root ansible_host=10.180.156.90
on-n81 ansible_ssh_user=root ansible_host=10.180.156.81
on-n82 ansible_ssh_user=root ansible_host=10.180.156.82
[controller_group]
on-ctl
[edgenode_group]
on-n81
on-n82
[edgenode_vca_group]
----8<---- inventory.ini -------- 8<-------

host_vars  configuration customisation (identical for controller and both edge nodes)

kernel_skip: true
hugepage_size: "2M" # Or 1G
hugepage_amount: "1500"
default_grub_params: "hugepagesz={{ hugepage_size }} hugepages={{ hugepage_amount }} "
additional_grub_params: ""
tuned_skip: true

**Comment by amr-mokhtar** [comment]
For on-premises, you'll have to re-deploy if the machines got rebooted.
Regarding docker service, I didn't see that happening in my experience. Were you able to extract any logs from the docker service identifying what caused it to stop? OpenNESS does not intervene with docker service execution.
