### ISSUE TITLE
Command tool "go mod download" fails

### ISSUE THREAD

**Issue by hui2980** [open-ness/edgenode#19]
When using command tool "go mod download" to cache all third-party dependency libraries, it failed while go version was 1.14, but if the go version was lower than 1.14, command tool "go mod download" would work right.

> [root@controller edgenode]# gvm use go1.14
> Now using version go1.14
> [root@controller edgenode]# go version
> go version go1.14 linux/amd64
> [root@controller edgenode]# go mod download
> go: errors parsing go.mod:
> /root/edgenode/go.mod:6: usage: go 1.23
> [root@controller edgenode]#

**Comment by tongtongxiaopeng1979** [comment]
@hui2980  from the logs, the issue happen with edgecontroller rather than edgenode.

you observe the similar issues for edgenode repo?

**Comment by hui2980** [comment]
@tongtongxiaopeng1979  Yes, I tried the command "go mod download" under the edgenode project. The logs was incorrect , and   I updated that just now, Sorry for that.

**Comment by tongtongxiaopeng1979** [comment]
@hui2980  the workaround can be using go1.14 in go.mod as you pointed out.

i will close it since it is already verified on your side
