### ISSUE TITLE
Kernel issuse

### ISSUE THREAD

**Issue by nandeesh54** [open-ness/edgenode#3]
kernel is crashing in centos after reboot once setup script is finished in virtual box

**Comment by w910820618** [comment]
> kernel is crashing in centos after reboot once setup script is finished in virtual box

I also encountered the same problem. Do you have a solution?

**Comment by amr-mokhtar** [comment]
OpenNESS edge node assumes > 100GB of RAM installed on your setup, this memory is allocated to hugepages.
To overcome this problem:

1. Reboot the Intel Xeon server
2. Press “Esc” to intercept this countdown and enter the GRUB menu
3. Select the CentOS RT kernel and press “e” to edit
4. Search for `hugepages=50000` and replace it with `hugepages=10000` – this allocates 20GB hugepages
5. Boot up the machine with the new values, you should be able to get the kernel booting well.
6. Remember to edit the grub with the same change to make it permanent (details on editing grub is explained [here](https://www.thegeekdiary.com/centos-rhel-7-grub2-configuration-file-bootgrub2grub-cfg-explained/))
