### ISSUE TITLE
error when running 03_build_and_deploy.sh

### ISSUE THREAD

**Issue by hjwoohakimwhj** [open-ness/edgenode#4]
Hi, when I ran 03_build_and_deploy.sh, the script terminated at "Building images" step. So following by your instructions, I ran ./scripts/ansible/common/scripts/reinstall-urllib3-module.sh and then re-run 03_build_and_deploy.sh. However, it seemd like it did not work. Could you please tell me how to fix it? The output is as follows. Thank you very much!

TASK [Build images] *****************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "source /etc/profile && RTE_SDK=/opt/dpdk-18.08 RTE_TARGET=x86_64-native-linuxapp-gcc make build-docker", "delta": "0:00:53.418771", "end": "2019-10-08 10:52:02.253623", "msg": "non-zero return code", "rc": 2, "start": "2019-10-08 10:51:08.834852", "stderr": "/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!\n  RequestsDependencyWarning)\nThe NTS_MEM_MB_S0 variable is not set. Defaulting to a blank string.\nThe NTS_MEM_MB_S1 variable is not set. Defaulting to a blank string.\nThe REMOTE_SYSLOG_IP variable is not set. Defaulting to a blank string.\nsyslog-ng uses an image, skipping\nBuilding edgednssvr\nService 'edgednssvr' failed to build: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\nmake: *** [build-docker] Error 1", "stderr_lines": ["/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!", "  RequestsDependencyWarning)", "The NTS_MEM_MB_S0 variable is not set. Defaulting to a blank string.", "The NTS_MEM_MB_S1 variable is not set. Defaulting to a blank string.", "The REMOTE_SYSLOG_IP variable is not set. Defaulting to a blank string.", "syslog-ng uses an image, skipping", "Building edgednssvr", "Service 'edgednssvr' failed to build: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "make: *** [build-docker] Error 1"], "stdout": "make -C internal/nts/eda_libs\nmake[1]: Entering directory `/root/edgenode/internal/nts/eda_libs'\nmake[1]: `build' is up to date.\nmake[1]: Leaving directory `/root/edgenode/internal/nts/eda_libs'\nmkdir -p \"dist\"\nGOOS=linux go build -o \"dist/appliance\" ./cmd/appliance\nmkdir -p \"dist\"\nGOOS=linux go build -a --ldflags '-extldflags \"-static\"' -tags netgo -installsuffix netgo -o \"dist/edgednssvr\" ./cmd/edgednssvr\nmake -C internal/nts\nmake[1]: Entering directory `/root/edgenode/internal/nts'\n== libs\n== libnes_api\nmake[4]: Nothing to be done for `libnes_sq.o'.\n== libnes_cfgfile\n== libnes_daemon\n== libnes_lookup\n== libnes_queue\n== libnes_sq\n== libnes_acl\n== libnes_api_shared\nmake[4]: Nothing to be done for `libnes_api.o'.\n/root/edgenode/internal/nts//build/lib must be added to /etc/ld.so.conf or LD_LIBRARY_PATH variable to allow binary to link with dynamic library\n== daemon\nmake[3]: Nothing to be done for `nis_io.o'.\n== client\nmake[1]: Leaving directory `/root/edgenode/internal/nts'\ncp build/appliance/Dockerfile \"/tmp/tmp.5HO3pXV7ty/Dockerfile_appliance\"\ncp build/appliance/entrypoint.sh \"/tmp/tmp.5HO3pXV7ty\"\ncp /opt/dpdk-18.08/usertools/dpdk-devbind.py \"/tmp/tmp.5HO3pXV7ty\"\ncp \"dist/appliance\" \"/tmp/tmp.5HO3pXV7ty\"\ncp build/edgednssvr/Dockerfile \"/tmp/tmp.5HO3pXV7ty/Dockerfile_edgednssvr\"\ncp \"dist/edgednssvr\" \"/tmp/tmp.5HO3pXV7ty\"\nmkdir -p \"/tmp/tmp.5HO3pXV7ty/nts\"\ncp internal/nts/build/nes-daemon \"/tmp/tmp.5HO3pXV7ty/nts\"\ncp internal/nts/kni_docker_daemon.py \"/tmp/tmp.5HO3pXV7ty/nts\"\ncp internal/nts/entrypoint.sh \"/tmp/tmp.5HO3pXV7ty/nts\"\ncp internal/nts/build/libnes_api_shared.so \"/tmp/tmp.5HO3pXV7ty/nts\"\ncp internal/nts/Dockerfile \"/tmp/tmp.5HO3pXV7ty/Dockerfile_nts\"\ncp docker-compose.yml \"/tmp/tmp.5HO3pXV7ty\"\ncd \"/tmp/tmp.5HO3pXV7ty\" && VER=1.0 docker-compose build\nStep 1/5 : FROM alpine:latest", "stdout_lines": ["make -C internal/nts/eda_libs", "make[1]: Entering directory `/root/edgenode/internal/nts/eda_libs'", "make[1]: `build' is up to date.", "make[1]: Leaving directory `/root/edgenode/internal/nts/eda_libs'", "mkdir -p \"dist\"", "GOOS=linux go build -o \"dist/appliance\" ./cmd/appliance", "mkdir -p \"dist\"", "GOOS=linux go build -a --ldflags '-extldflags \"-static\"' -tags netgo -installsuffix netgo -o \"dist/edgednssvr\" ./cmd/edgednssvr", "make -C internal/nts", "make[1]: Entering directory `/root/edgenode/internal/nts'", "== libs", "== libnes_api", "make[4]: Nothing to be done for `libnes_sq.o'.", "== libnes_cfgfile", "== libnes_daemon", "== libnes_lookup", "== libnes_queue", "== libnes_sq", "== libnes_acl", "== libnes_api_shared", "make[4]: Nothing to be done for `libnes_api.o'.", "/root/edgenode/internal/nts//build/lib must be added to /etc/ld.so.conf or LD_LIBRARY_PATH variable to allow binary to link with dynamic library", "== daemon", "make[3]: Nothing to be done for `nis_io.o'.", "== client", "make[1]: Leaving directory `/root/edgenode/internal/nts'", "cp build/appliance/Dockerfile \"/tmp/tmp.5HO3pXV7ty/Dockerfile_appliance\"", "cp build/appliance/entrypoint.sh \"/tmp/tmp.5HO3pXV7ty\"", "cp /opt/dpdk-18.08/usertools/dpdk-devbind.py \"/tmp/tmp.5HO3pXV7ty\"", "cp \"dist/appliance\" \"/tmp/tmp.5HO3pXV7ty\"", "cp build/edgednssvr/Dockerfile \"/tmp/tmp.5HO3pXV7ty/Dockerfile_edgednssvr\"", "cp \"dist/edgednssvr\" \"/tmp/tmp.5HO3pXV7ty\"", "mkdir -p \"/tmp/tmp.5HO3pXV7ty/nts\"", "cp internal/nts/build/nes-daemon \"/tmp/tmp.5HO3pXV7ty/nts\"", "cp internal/nts/kni_docker_daemon.py \"/tmp/tmp.5HO3pXV7ty/nts\"", "cp internal/nts/entrypoint.sh \"/tmp/tmp.5HO3pXV7ty/nts\"", "cp internal/nts/build/libnes_api_shared.so \"/tmp/tmp.5HO3pXV7ty/nts\"", "cp internal/nts/Dockerfile \"/tmp/tmp.5HO3pXV7ty/Dockerfile_nts\"", "cp docker-compose.yml \"/tmp/tmp.5HO3pXV7ty\"", "cd \"/tmp/tmp.5HO3pXV7ty\" && VER=1.0 docker-compose build", "Step 1/5 : FROM alpine:latest"]} 
PLAY RECAP **************************************************************************************************************************
127.0.0.1                  : ok=30   changed=5    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0

**Comment by dekaremania** [comment]
Did you solve this issue?

**Comment by hjwoohakim** [comment]
It seems like the pull of images cost a lot of time, so the installation will be failed. So I created the images beforehand according to their Dockerfiles and saved them using "docker save XX". When I ran script 3 again, I used "docker load XX" at the same time.

**Comment by dekaremania** [comment]
> It seems like the pull of images cost a lot of time, so the installation will be failed. So I created the images beforehand according to their Dockerfiles and saved them using "docker save XX". When I ran script 3 again, I used "docker load XX" at the same time.

could you give an example how to create images beforehand according to their Dockerfiles and saved them? sorry i am noobs

**Comment by hjwoohakim** [comment]
Hi. Take a container named "edgenode_appliance_1“ which will be instantiated in our edgenode as an example. Its Dockerfile is located in edgenode/build/appliance/Dockerfile. In this Dockerfile, some steps will take some time, especially for the people in China. So we can build a image named XX which finishes all steps required to download something. And then the first line of appliance's Dockerfile can be replaced with "FROM XX". What's more, we need to save this new image as XX.tar by running "docker save your image id -o XX.tar", because each time script 3 runs, it will destroy all images. After script 3 destroys all images, we can run "docker load -i XX.tar" and then the container named "edgenode_appliance_1“ will be deployed quickly.
I am not familied with docker and openness, so there must be something more useful measures...If you know, I will appreciate if  you could share with me~~

**Comment by dekaremania** [comment]
> Hi. Take a container named "edgenode_appliance_1“ which will be instantiated in our edgenode as an example. Its Dockerfile is located in edgenode/build/appliance/Dockerfile. In this Dockerfile, some steps will take some time, especially for the people in China. So we can build a image named XX which finishes all steps required to download something. And then the first line of appliance's Dockerfile can be replaced with "FROM XX". What's more, we need to save this new image as XX.tar by running "docker save your image id -o XX.tar", because each time script 3 runs, it will destroy all images. After script 3 destroys all images, we can run "docker load -i XX.tar" and then the container named "edgenode_appliance_1“ will be deployed quickly.
> I am not familied with docker and openness, so there must be something more useful measures...If you know, I will appreciate if you could share with me~~

Now i created appliance, edgednssvr, alpine, centos7.6. however the 03_build_and_deploy.sh script still build those images and still error. Do you know how to skip the image building?

**Comment by hjwoohakim** [comment]
> > Hi. Take a container named "edgenode_appliance_1“ which will be instantiated in our edgenode as an example. Its Dockerfile is located in edgenode/build/appliance/Dockerfile. In this Dockerfile, some steps will take some time, especially for the people in China. So we can build a image named XX which finishes all steps required to download something. And then the first line of appliance's Dockerfile can be replaced with "FROM XX". What's more, we need to save this new image as XX.tar by running "docker save your image id -o XX.tar", because each time script 3 runs, it will destroy all images. After script 3 destroys all images, we can run "docker load -i XX.tar" and then the container named "edgenode_appliance_1“ will be deployed quickly.
> > I am not familied with docker and openness, so there must be something more useful measures...If you know, I will appreciate if you could share with me~~
> 
> Now i created appliance, edgednssvr, alpine, centos7.6. however the 03_build_and_deploy.sh script still build those images and still error. Do you know how to skip the image building?

Hi, it seems like edgenode will destroy all images when 03_build_and_deploy.sh runs, and then download new images. My method is that when they were destroyed, I opened **another terminal** and run docker load, and then 03_build_and_deploy.sh detect the images and do not download again.
