### ISSUE TITLE
Unable to view ring traffic records through nes_client

### ISSUE THREAD

**Issue by rogerogerogeroger** [open-ness/edgenode#7]
(nes_client) # show rings
ID:     Name:                   Received:                       Sent:          Dropped Ring Full:           Dropped No Route: 
 0  NIS_UPSTR_GTPU                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 1  NIS_UPSTR_GTPC                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 2  NIS_UPSTR_RNIS                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 3  NIS_UPSTR_SCTP                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 4  NIS_DWSTR_GTPU                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 5  NIS_DWSTR_GTPC                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 6  NIS_DWSTR_RNIS                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 7  NIS_DWSTR_SCTP                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 8  NTS_UPSTR_GTPU                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
 9  NTS_DWSTR_GTPU                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
10    NTS_UPSTR_IP                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
11    NTS_DWSTR_IP                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
12     NTS_LBP_ANY                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
13   PORT_0_IO_ANY                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
14   PORT_1_IO_ANY                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts
15   PORT_2_IO_ANY                    N/A pkts                    N/A pkts                    N/A pkts                    N/A pkts

**Comment by hjwoohakim** [comment]
I ran nes_client in edgenode/internal/nts/client/build/nes_client. But it can show that Connection with server is not established! Could you please tell me how can I connect with server? Thanks a lot.

**Comment by anurag-ness** [comment]
Hi hjwoohakim, did you manage to resolve above?

It is an internal config file - so please beware it can change. Now that you are warned, please search for nts.cfg file and export to NES_SERVER_CONF prior to starting the nes_client. For example please see if the following commands works 
```
# export NES_SERVER_CONF=/var/lib/appliance/nts/nts.cfg
# /opt/edgenode/internal/nts/client/build/nes_client 
```

Then at the command prompt use "connect" as below:

```
[root@mynode01~]# /opt/edgenode/internal/nts/client/build/nes_client 
# connect
Connection is established.
# 
```

**Comment by amr-mokhtar** [comment]
Hi @hjwoohakim @rogerogerogeroger, Are you still experiencing these errors? Do you still need support with them?

**Comment by rogerogerogeroger** [comment]
@amr-mokhtar Is the `show rings` command currently unavailable? Like the output I listed above, I can only see the status of `N/A`

**Comment by amr-mokhtar** [comment]
@rogerogerogeroger.. To be able to view rings' stats, add the flag `CFLAGS += -DRSTATS` to edgenode/internal/nts/daemon/Makefile, then rebuild & redeploy.

**Comment by rogerogerogeroger** [comment]
@amr-mokhtar Thanks, I noticed this FLAGS！！

**Comment by amr-mokhtar** [comment]
Awesome!
